/* Generated by MyraPad at 7/4/2025 7:57:18 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace NesNes.Host.UI
{
	partial class DebuggerUI: VerticalStackPanel
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Emulation";

			start = new MenuItem();
			start.Text = "Start";
			start.Id = "start";

			pause = new MenuItem();
			pause.Text = "Pause";
			pause.Id = "pause";

			var menuSeparator1 = new MenuSeparator();

			reset = new MenuItem();
			reset.Text = "Reset";
			reset.Id = "reset";

			emulation = new HorizontalMenu();
			emulation.MouseCursor = Myra.Graphics2D.UI.MouseCursorType.Hand;
			emulation.Id = "emulation";
			emulation.Items.Add(start);
			emulation.Items.Add(pause);
			emulation.Items.Add(menuSeparator1);
			emulation.Items.Add(reset);

			var label2 = new Label();
			label2.Text = "Step by";

			stepInstruction = new MenuItem();
			stepInstruction.Text = "Instruction";
			stepInstruction.Id = "stepInstruction";

			var menuSeparator2 = new MenuSeparator();

			stepPixel = new MenuItem();
			stepPixel.Text = "Pixel";
			stepPixel.Id = "stepPixel";

			stepScanline = new MenuItem();
			stepScanline.Text = "Scanline";
			stepScanline.Id = "stepScanline";

			stepFrame = new MenuItem();
			stepFrame.Text = "Frame";
			stepFrame.Id = "stepFrame";

			stepBy = new HorizontalMenu();
			stepBy.MouseCursor = Myra.Graphics2D.UI.MouseCursorType.Hand;
			stepBy.Id = "stepBy";
			stepBy.Items.Add(stepInstruction);
			stepBy.Items.Add(menuSeparator2);
			stepBy.Items.Add(stepPixel);
			stepBy.Items.Add(stepScanline);
			stepBy.Items.Add(stepFrame);

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 4;
			horizontalStackPanel1.Widgets.Add(label1);
			horizontalStackPanel1.Widgets.Add(emulation);
			horizontalStackPanel1.Widgets.Add(label2);
			horizontalStackPanel1.Widgets.Add(stepBy);

			var listView1 = new ListView();
			listView1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			listView1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			StackPanel.SetProportionType(listView1, Myra.Graphics2D.UI.ProportionType.Fill);

			
			Spacing = 4;
			VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			Height = 200;
			Padding = new Thickness(4);
			Widgets.Add(horizontalStackPanel1);
			Widgets.Add(listView1);
		}

		
		public MenuItem start;
		public MenuItem pause;
		public MenuItem reset;
		public HorizontalMenu emulation;
		public MenuItem stepInstruction;
		public MenuItem stepPixel;
		public MenuItem stepScanline;
		public MenuItem stepFrame;
		public HorizontalMenu stepBy;
	}
}
